version: '3'

services:
  app:
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 1m40s docker-entrypoint.sh
    build:
      context: node
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000"
    depends_on:
      - db
    command: bash -c "npm install && node index.js"
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: nodedb
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha_do_usuario
    volumes:
      - ./mysql:/var/lib/mysql
      - ./preConfigMysql.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - node-network
    user: "1000:1000"

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - node-network
networks:
  node-network:
    driver: bridge